[package]
name = "scaramanga"
version = "0.2.2"
authors = ["Shempignon <nicolas@pointndots.com>"]
edition = "2021"

[dependencies]
reqwest = "0.11.10"
tokio = { version = "1.19.2", features = ["full"] }
which = "4.2.5"
log = "0.4.17"
pretty_env_logger = "0.4.0"
toml = "0.5.9"
serde = { version = "1.0.137", features = ["derive"] }
simple-error = "0.2.3"
chrono = "0.4.19"
uname = "0.1.1"
futures = "0.3.21"

[dev-dependencies]
httpmock = "0.6.6"
lazy_static = "1.4.0"
