[package]
name = "scaramanga"
version = "0.2.1"
authors = ["Shempignon <nicolas@pointndots.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10"
tokio = { version = "0.2", features = ["full"] }
which = "4.0"
log = "0.4"
pretty_env_logger = "0.4"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
simple-error = "0.2"
chrono = "0.4"
uname = "0.1"
futures = "0.3"

[dev-dependencies]
httpmock = "0.5"
lazy_static = "1.4"
