[package]
name = "scaramanga"
version = "0.3.0"
authors = ["Shempignon <nicolas@pointndots.com>"]
edition = "2021"

[dependencies]
futures = "0.3.26"
log = "0.4.17"
pretty_env_logger = "0.4.0"
reqwest = "0.11.14"
serde = { version = "1.0.152", features = ["derive"] }
simple-error = "0.2.3"
time = { version = "0.3.17", features = ["formatting"] }
tokio = { version = "1.25", features = ["full"] }
toml = "0.7.2"

[dev-dependencies]
httpmock = "0.6.7"
lazy_static = "1.4.0"
